name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, check_args: 'c("--no-manual", "--no-tests", "--no-examples")'}
          - {os: macos-latest, check_args: 'c("--no-manual")'}
          - {os: windows-latest, check_args: 'c("--no-manual", "--no-tests", "--no-examples")'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: ${{ matrix.config.check_args }}
          upload-snapshots: true
